symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600         # lien valide 1 heure
    throttle_limit: 2      # max 2 demandes par heure par email
    enable_garbage_collection: true
